In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [4]:
pip install sb_utils

ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <4.0,>=3.12; 0.1.1 Requires-Python <4.0,>=3.12
ERROR: Could not find a version that satisfies the requirement sb_utils (from versions: none)
ERROR: No matching distribution found for sb_utils
Note: you may need to restart the kernel to use updated packages.

In [5]:
from library.sb_utils import save_file

ModuleNotFoundError: No module named 'library'

In [7]:
first_data = pd.read_csv('diabetes_data_upload.csv')

In [30]:
first_data.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [21]:
first_data.shape

(520, 17)

In [15]:
first_data.dtypes

Age                    int64
Gender                object
Polyuria              object
Polydipsia            object
sudden weight loss    object
weakness              object
Polyphagia            object
Genital thrush        object
visual blurring       object
Itching               object
Irritability          object
delayed healing       object
partial paresis       object
muscle stiffness      object
Alopecia              object
Obesity               object
class                 object
dtype: object

In [18]:
first_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: int64(1), object(16)
memory usage: 69.2+ KB

In [19]:
first_data.isna().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [25]:
first_data['Gender'].unique

<bound method Series.unique of 0        Male
1        Male
2        Male
3        Male
4        Male
        ...
515    Female
516    Female
517    Female
518    Female
519      Male
Name: Gender, Length: 520, dtype: object>

In [28]:
first_data.describe()

              Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

In [29]:
first_data.count()

Age                   520
Gender                520
Polyuria              520
Polydipsia            520
sudden weight loss    520
weakness              520
Polyphagia            520
Genital thrush        520
visual blurring       520
Itching               520
Irritability          520
delayed healing       520
partial paresis       520
muscle stiffness      520
Alopecia              520
Obesity               520
class                 520
dtype: int64

In [31]:
first_data.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [67]:
symptom_list = ['Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching', 'Irritability', 'delayed healing', 'partial paresis', 'muscle stiffness', 'Alopecia', 'Obesity', 'class']

In [71]:
cleaned_data = pd.melt(first_data, id_vars= ['Gender', 'Age'],value_vars=symptom_list)

In [73]:
cleaned_data.tail()

      Gender  Age variable     value
7795  Female   39    class  Positive
7796  Female   48    class  Positive
7797  Female   58    class  Positive
7798  Female   32    class  Negative
7799    Male   42    class  Negative

In [32]:
mappings = {'Male': 1, 'Female': 2, 'Yes': 1, 
            'No': 2, 'Positive': 1, 
            'Negative': 2}
scored_data = first_data.replace(mappings)

In [33]:
scored_data.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,1,2,1,2,1,2,2,2,1,2,1,2,1,1,1,1
1,58,1,2,2,2,1,2,2,1,2,2,2,1,2,1,2,1
2,41,1,1,2,2,1,1,2,2,1,2,1,2,1,1,2,1
3,45,1,2,2,1,1,1,1,2,1,2,1,2,2,2,2,1
4,60,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1

In [34]:
scored_data.describe()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
count,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000,520.000000
mean,48.028846,1.369231,1.503846,1.551923,1.582692,1.413462,1.544231,1.776923,1.551923,1.513462,1.757692,1.540385,1.569231,1.625000,1.655769,1.830769,1.384615
std,12.151466,0.483061,0.500467,0.497776,0.493589,0.492928,0.498519,0.416710,0.497776,0.500300,0.428892,0.498846,0.495661,0.484589,0.475574,0.375317,0.486973
min,16.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,39.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000
50%,47.500000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000
75%,57.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,90.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [36]:
print(scored_data.value_counts())

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  Polyphagia  Genital thrush  visual blurring  Itching  Irritability  delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  class
30   1       2         2           2                   2         2           2               2                2        2             2                2                2                 2         2        2        16
46   1       2         2           2                   1         2           2               2                1        2             1                2                2                 1         2        2         7
53   1       2         2           2                   1         1           2               1                1        2             1                1                1                 1         2        2         7
38   1       2         2           2                   2         2           2               2                2        2             2                2                2                 2         2        2         7
48   2       1         1           1                   1         1           2               2                2        2             2                1                2                 2         2        1         6
                                                                                                                                                                                                                     ..
38   2       1         1           1                   1         1           2               2                2        2             2                1                2                 2         2        1         1
53   2       2         2           1                   1         2           2               1                1        2             1                2                2                 2         2        1         1
                                   2                   2         1           2               1                2        2             2                1                2                 2         2        1         1
38   1       1         2           1                   1         2           2               2                2        2             2                2                2                 2         2        1         1
16   1       1         2           1                   2         1           2               2                2        2             2                2                2                 2         2        1         1
Name: count, Length: 251, dtype: int64